declare type Color = {
    50: string;
    100: string;
    200: string;
    300: string;
    400: string;
    500: string;
    600: string;
    700: string;
    800: string;
    900: string;
};
export declare const turquoise: Color;
export declare const greenSea: Color;
export declare const emerald: Color;
export declare const nephritis: Color;
export declare const peterRiver: Color;
export declare const belizeHole: Color;
export declare const amethyst: Color;
export declare const wisteria: Color;
export declare const wetAsphalt: Color;
export declare const midnightBlue: Color;
export declare const sunflower: Color;
export declare const orange: Color;
export declare const carrot: Color;
export declare const pumpkin: Color;
export declare const alizarin: Color;
export declare const pomegranate: Color;
export declare const clouds: Color;
export declare const silver: Color;
export declare const concrete: Color;
export declare const asbestos: Color;
export {};
